# Welcome to Jekyll!
# 'bundle exec jekyll serve'

# title: Ananda's 
title: idek
author: Ananda Badari
email: badari.ananda@gmail.com
description: Portfolio of Ananda Badari
url: "https://blog.anandabadari.com/"
baseurl: ""
github_username:  abadari3
permalink: /:slug.html
future: true

# favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)

# Build settings
remote_theme: riggraz/no-style-please
plugins:
  - jekyll-feed
  - jekyll-target-blank

theme_config:
  back_home_text: ".."
  date_format: " "
  appearance: "auto"
  show_description: false

sass:
  style: :compressed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
